version: "3.8"

services:
  app:
    container_name: workspace-tomcat
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    environment:
      - TZ=Asia/Seoul
    port:
      - 9999:8080
    depends_on:
      - database
      
  database:
    container_name: workspace-db
    image: mysql:8.0
    hostname: workspace-mysql
    port:
      - 3307:3306
    environment:
      MYSQL_DATABASE: workspace
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 1111